services:
  - type: web
    name: django-app
    env: python
    plan: free  # or standard depending on your plan
    buildCommand: pip install -r requirements.txt
    startCommand: "waitress-serve --port=$PORT stpa.wsgi:application"
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: your_project_name.settings
      - key: SECRET_KEY
        sync: false  # Set to false so you can manage this in Render's dashboard
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
    region: oregon  # Select your preferred region